#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <windows.h>
#include <Lmcons.h>
#define BUFFER_SIZE 50
const char *titluProgram = "\n		920 Imnuri Executador PPS v2.1 by DaniS\n		HELP COMMAND AVAIBLE + REGISTRU ISTORIAL\n\n";

typedef char String[100];

String nombres[] = {
	"001.Plecati-va lui Dumnezeu",
	"002.Aleluia! Amin (canon)",
	"003.Spre slava Ta uniti",
	"004.Dumnezeu e mare!",
	"005.Dragoste divina",
	"006.Sfant si-nfricosat",
	"007.Ti-nalt,Iehova-n veci cantare",
	"008.In cerul ’nalt, de slava plin!",
	"009.Mare esti Tu,Doamne!",
	"010.Numele Tau minunat",
	"011.Preasfinte Creator!",
	"012.Ce mare este Dumnezeu!",
	"013.Domnul e bun",
	"014.Binecuvanta pe Domnul!",
	"015.Cand cerul nu era facut!",
	"016.Cantati marire-n cor!",
	"017.Doamne sfinte,Te marim!",
	"018.Iehova-i din veac",
	"019.Lauda,suflete,pe Domnul!",
	"020.Slava,slava",
	"021.Un imn de slava",
	"022.Mariti pe Domnul",
	"023.Mariti dun suflet,mariti pe Domnul!",
	"024.Mariti pe Isus prin cantare!",
	"025.Voi,credinciosi,veniti!",
	"026.Ne plecam in adorare",
	"027.Osanale!Aleluia!",
	"028.Osana!Osana",
	"029.Dati slava!(canon)",
	"030.Pentru tot ce ai creat",
	"031.Prin imnuri sfinte",
	"032.Sa-L laudam pe Dumnezeu!",
	"033.Ca Domnu-n lume(canon)",
	"034.Spre Cel din slavi",
	"035.Tata ceresc,ce mult am vrea",
	"036.Slava,slava Celui Sfant",
	"037.Slaviti pe Domnul!",
	"038.Te-adoram cu bucurie!",
	"039.Slava azi si-n vesnicie",
	"040.Laudati pe Domnul slavei!",
	"041.Marire Tie,Doamne sfant!",
	"042.Cu slava Ta,Parinte sfant",
	"043.Multumiti lui Dumnezeu",
	"044.Tata iubit,Te-adoram",
	"045.Marim pe Cel Sfant",
	"046.Sfinte Parinte,ramai intre noi!",
	"047.Slavim pe Dumnezeu",
	"048.Mariti pe Domnul ne-ncetat!",
	"049.Slava si glorie lui Dumnezeu!(canon)",
	"050.Fii laudat,Isus Hristos",
	"051.Doar Dumnezeu va fi marit!",
	"052.Sa fie harul Domnului Hristos",
	"053.Sa-l laudam!",
	"054.Mariti pe Dumnezeu!",
	"055.Slavesc pe Dumnezeu",
	"056.Eu cred",
	"057.Cred intr-Unul Dumnezeu",
	"058.Vreau glasul sa-mi inalt voios",
	"059.Nimeni ca Tine",
	"060.O,vino,scump Isuse!",
	"061.Eu am un loc ce-mi place mult",
	"062.Vrem sa-L incoronam!",
	"063.Hristos e Cel ce va domni",
	"064.Mai sus decat inaltii munti",
	"065.Ieri,Isus pe lemn muri",
	"066.Aleluia catre Domnul!",
	"067.Un Nume ca al nimanui",
	"068.Cladim pe o Stanca de mult pret",
	"069.Ca roua din zori",
	"070.Cuvant dumnezeiesc",
	"071.Veste buna-avem de sus",
	"072.Domnu-i iubirea",
	"073.De-a lungul marilor vecii",
	"074.Cine,ca Isus,mai poate",
	"075.Doar tu ne esti cale,adevar si viata",
	"076.Iubire sfanta,dar ceresc",
	"077.Iubit-ai,Doamne,intreaga omenire",
	"078.Prin altul nu poti fi scapat",
	"079.Un singur Nume vreau s-aud",
	"080.O,Isus,ce dulce nume!",
	"081.Nu-i decat un singur Nume",
	"082.Nume frumos",
	"083.Isuse,Tu esti viata",
	"084.Doamne,Tu mi-esti bucuria!",
	"085.Isus,ca Fiu de Dumnezeu",
	"086.Isus imi e Pastorul bun",
	"087.Eu am un scump Prieten",
	"088.Mai sus de cerul instelat",
	"089.Isus e cel mai bun Prieten",
	"090.Isus,Prieten minunat",
	"091.Al meu esti,Isuse",
	"092.Vreau sa fiu in veci cu Domnul",
	"093.Adesea sub bolta-norata",
	"094.Isus,ce mult Tu m-ai iubit",
	"095.Ca apa in pustie",
	"096.De ce sa nu cant intruna",
	"097.Cat va trai Hristos",
	"098.Din radacina vie",
	"099.Azi avem Mantuitor",
	"200.Am venit la Tine,Doamne!",
	"201.Am fost iertat de Dumnezeu",
	"202.Azi ma gasesc langa Iordan",
	"203.Mi-e inima aprins altar",
	"204.Azi voiosi tresalta",
	"205.Haine albe(canon)",
	"206.Sigur la Domnu-n brate",
	"207.O poarta-n ceruri s-a deschis",
	"208.Stiu ca sunt mantuit prin Tine",
	"209.Nu jertfe,nici onoare",
	"210.Eu sunt inscris in Cartea vietii",
	"211.Nimeni ca Tine pe pamant",
	"212.Isus imi zice bland",
	"213.Ma-ncred in Tine,Domnul meu!",
	"214.Suflete,in praf te pleaca!",
	"215.Din Dumnezeu cel sfant",
	"216.Traieste-acelasi Dumnezeu",
	"217.O,condu-ma Tu,Isuse!",
	"218.Ce dulce-i,Doamne,pacea Ta!",
	"219.Cred in Domnul Isus",
	"220.Cel ce in Tatal se increde",
	"221.Stau pe Adevar",
	"222.Tu esti Doamne-a pacii Stanca",
	"223.Ce face Domnul,totu-i bun!",
	"224.Suflet slab,asteapta pe Dumnezeu!",
	"225.In toate-n a mea viata",
	"226.O singura speranta",
	"227.Dumnezeu ne e salvare",
	"228.Fericit e tot acela",
	"229.Crede,frate-n orice zi!",
	"230.Zi de zi si-n fiecare clipa",
	"231.Eu vin zi de zi",
	"232.Isus si eu",
	"233.Langa Isus",
	"234.Sfant izvor ceresc",
	"235.Domnul mi-este calauza",
	"236.Daca vrabii pot sa cada",
	"237.Frumos e s-ascult",
	"238.De iubesti pe Domnul",
	"239.Ce te framanti,inima mea",
	"240.Cand pacea iti lipseste",
	"241.Daca neguri vin ades",
	"242.Cand neguri se-aduna",
	"243.Bland,ca o voce de inger",
	"244.Ce bine e in viata!(canon)",
	"245.Bine e sa crezi in Domnul",
	"246.Pe Stanca cea tare",
	"247.Spre culmi de munte",
	"248.Doamne,spre Tine privim!",
	"249.Poti sa te-ncrezi in Isus",
	"250.Speranta mea e doar Hristos",
	"251.O,suflete,stai linistit!",
	"252.De mana du-ma,Tata!",
	"253.Pretutindeni cu Isus",
	"254.Pe veci cu Dumnezeu!",
	"255.Apartin lui Isus",
	"256.Domnu-i Pastorul meu(canon)",
	"257.Parintele meu e foarte bogat",
	"258.Din Sinai a rasunat",
	"259.Cuvantul Legii lui Isus",
	"260.Placuta-i Doamne,Legea Ta!",
	"261.Vointa si indeplinirea",
	"262.Sa pazesc,Isuse-nvata-ma,Legea Ta!",
	"263.Privesc la Tine,Domnul meu!",
	"264.Ca un rau de viata",
	"265.Daca Domnul e-a ta desfatare",
	"266.De-acum sunt gata",
	"267.Domnul ne cheama pe munte",
	"268.Cetate tare-i Dumnezeu",
	"269.Iubit Isuse-al meu",
	"270.In Domnul gasesc adapost",
	"271.Jan Hus(canon)",
	"272.Va-ndreptati spre Ghetsimani!",
	"273.Mergem inainte!",
	"274.Biruitorul",
	"275.Cand David si cu Goliat(canon)",
	"276.Il vad adesea si-l admir",
	"277.Furtuna de-ar lovi",
	"278.Auzi,Doamne,urletul marii",
	"279.Plutim prin furtuna",
	"280.Indrazneste cu credinta!",
	"281.Nainte cu Isus",
	"282.Au fost eroi",
	"283.Pe aripi de vultur",
	"284.Ramai cu noi,Isus iubit!",
	"285.Drumul sfintelor victorii",
	"286.Cine vrea smerit sa fie(canon)",
	"287.Fiti tari in credinta!",
	"288.Mica picatura",
	"289.Lumina-i Hristos",
	"290.Daca crezi in Dumnezeu",
	"291.Stai tare-n ispite!",
	"292.Sus,oaste-a lui Hristos!",
	"293.Nu ceda ispitei!",
	"294.Cand te-atrage o ispita",
	"295.De mult ma lupt s-ajung mai sus",
	"296.Daca crucea grea iti pare",
	"297.Cand sunt rapus",
	"298.Oricum va fi",
	"299.Ca sa fi bun crestin",
	"300.Cerul ne tot cheama",
	"301.Noi calatori suntem",
	"302.Voi,crestini,sculati!",
	"303.Langa crucea ta,Isuse",
	"304.De vrei sa fi biruitor",
	"305.Sunt eu crestin adevarat",
	"306.De n-as avea in Domnul mangaiere",
	"307.Numai Tu,Isuse!",
	"308.Spre cine sa ma-ndrept",
	"309.Mai langa tronul Tau",
	"310.Esti pacea mea!",
	"311.Cand te-apasa greutati",
	"312.Cum doreste cerbul apa",
	"313.Un vis prea scurt",
	"314.Doamne,cata suferinta!",
	"315.De ce lacrimi arzatoare",
	"316.Cand val de durere",
	"317.Suferinta nu te-nvinge",
	"318.Cand necazuri intalnesti",
	"319.Lauda astazi pe Domnul!",
	"320.Obosit si frant de cale lunga",
	"321.Din cerul slavit",
	"322.Cand nimeni nu m-ajuta",
	"323.De sus,din slava senina",
	"324.Doamne,pe Tine te-astept!",
	"325.Tata,toti te rugam!",
	"326.Aripi da-mi,Isus iubit!",
	"327.Un singur lucru imi doresc",
	"328.Desi e lumea plina de minuni",
	"329.Doamne-ntine palma Ta",
	"330.O,Doamne pentru slava Ta",
	"331.O,blanda Stea",
	"332.Ramai cu noi!",
	"333.Cand Domnul Hristos",
	"334.Inima mea de-acum Ti-o daruiesc",
	"335.Iti predau intreaga viata",
	"336.Pe Isus Il vreau aproape",
	"337.Sfintirea mi-este tinta",
	"338.Glasul Tau cel bland",
	"339.Viata noastra",
	"340.Ridicati-ma-n credinta!",
	"341.Trec iute bucurii",
	"342.Fara de margini e dorinta mea",
	"343.Catre cer un dor m-atrage",
	"344.Doamne-as vrea sa stau...",
	"345.Dupa Domnul vietii",
	"346.Iubitul meu Mantuitor",
	"347.Tot mai aproape",
	"348.Gandul lui Hristos sa fie",
	"349.Pe Isus,cat mai devreme...",
	"350.Urmati-Mi-zice bland Hristos",
	"351.Voios pornesc in viata",
	"352.Pe Tine,Doamne-a mea tarie",
	"353.Doamne,slava Ta s-o stim",
	"354.Intr-aripat in mine",
	"355.Langa Tine,scump Isuse",
	"356.Ca un cerb setos de ape",
	"357.Doamne,Tu mereu ma-nvata!",
	"358.Doamne,da-mi Cuvantul Tau!",
	"359.O,Tata din ceruri!",
	"360.Doamne,ia Tu viata mea!",
	"361.Voia Ta,Doamne!",
	"362.Tata,azi Te rugm",
	"363.Vino,Isuse,azi in viata mea!",
	"364.Vino,Te-astept!",
	"365.Numai cu Isus voiesc a merge",
	"366.Fii azi cu mine,Domnul meu",
	"367.Niciunde fara Tine",
	"368.Simt un dor nespus,Isuse!",
	"369.Doamne,simt in piept o floare",
	"370.Mai mult sa Te iubesc",
	"371.Te-am vazut sub crucea grea",
	"372.Eu vreau pe Isus si iubirea Sa",
	"373.Podoaba si medalion",
	"374.Nu doresc alt bine,Doamne...",
	"375.Isus in lume a venit",
	"376.Bunul Isus ne-a invatat",
	"377.De zici,Iubesc pe Dumnezeu",
	"378.Poti avea credinta tare",
	"379.Pot ca ingerii sa zbor",
	"380.Fapta buna e-o comoara",
	"381.Cine-i gata",
	"382.Eu am nevoie-n orice zi",
	"383.Pentru cei bolnavi",
	"384.Doamne,Lumina lumii esti",
	"385.Doamne,fii  cu-al Tau popor",
	"386.Veniti caci vreau a spune!",
	"387.Ce fericire,am pe Isus!",
	"388.Frumoasa-i credinta(canon)",
	"389.Sa fie oare-adevarat",
	"390.Sus!Gata fii de lucru!(canon)",
	"391.O,cat iubit-a Dumnezeu!",
	"392.M-a aflat Pastorul nostru",
	"393.Nu doresc bogatie",
	"394.Cand primvara vine iar(canon)",
	"395.Suntem pe calea lui Isus",
	"396.In Cuvant Te-am aflat!",
	"397.Iertand a mea razvratire",
	"398.O,ce nespusa fericire!",
	"399.Sunt fericit!",
	"400.Isus,cat m-a iubit de mult!",
	"401.Eu vesel cant lui Dumnezeu",
	"402.Imi amintesc de-o scumpa zi",
	"403.Din groapa pieirii",
	"404.O,cat de orb am fost",
	"405.Este soare azi in viata mea",
	"406.Isus e-a mea cantare",
	"407.Cu tine,Domnul meu iubit",
	"408.Langa porti de vesnicii",
	"409.Voi,crestini,fiti totdeauna veseli!",
	"410.Iubirea ce ne face asa de fericiti",
	"411.Viata plina de lumina",
	"412.Vrei sa ajungi pe plaiuri ceresti",
	"413.Vesel salta,clocoteste",
	"414.Apa cristalina",
	"415.Vezi cum trei cu Daniel",
	"416.Fructe,legume(canon)",
	"417.Laudati!(canon)",
	"418.Lucrarea,Doamne,este-a Ta!",
	"419.Timpul scurt",
	"420.De pe Stanca mantuirii",
	"421.Sus,frate drag!",
	"422.Venim din Cuvantul de Domnul rostit",
	"423.Ce mare seceris!(canon)",
	"424.Bucuros ma gandesc la caminul ceresc",
	"425.Domnul ne-a dat prin apostoli",
	"426.Voi,servi,degraba-acum iesiti!",
	"427.Noi suntem bratele intinse",
	"428.Pentru cel ce inseteaza",
	"429.Iubirea lui Hristos ne-a adunat",
	"430.Mergeti la cei pierduti!",
	"431.Am invatat privind la tine",
	"432.Peste munti,peste mari",
	"433.In tari indepartate",
	"434.Cand Dumnezeu te cheama in lucrare",
	"435.In a Domnului lucrare",
	"436.Noi azi plecam in lucrare",
	"437.Plecam,Stapane-n via Ta",
	"438.Seamana samanta!",
	"439.As vrea sa duc in lume pacea Ta!",
	"440.Dorul meu ne-ncetat...",
	"441.Iata,vine Domnul nostru!(canon)",
	"442.Iata,granele-si pleaca spicele!",
	"443.Isuse,da-mi Cuvantul Tau!",
	"444.De ti-este greu pe cale",
	"445.Doamne,marea Ta lucrare!",
	"446.N-auzi tu cand zice Domnul",
	"447.Asa cum Eu am fost trimis",
	"448.Va cheama Hristos!",
	"449.In amurgul ce se lasa",
	"450.Zor deci ca vine noaptea!",
	"451.Hristos cheama-ajutoare",
	"452.Purtam cu noi lumini",
	"453.E timpul marii treziri",
	"454.Cand Domnul Isus azi ne cheama",
	"455.De ce nu vii ca sa ne iei la tine",
	"456.Oare n-ati aflat voi inca",
	"457.Vin la Isus azi.nu-ntarzia!",
	"458.Vino la apa de viata!",
	"459.Pentru Domnitorul pacii",
	"460.Pe viata Mea de Dumnezeu",
	"461.Dulcea chemare",
	"462.Intoarce-te,o,fiu pierdut!",
	"463.Zi de zi eu te chem",
	"464.O,voi,toti cei impovarati!",
	"465.Vin la Domnul cel iubit!",
	"466.O,sarmane om!",
	"467.I-auzi,bate tot mereu!",
	"468.Spre-a cele tarmuri din vesnicii",
	"469.Auzi cum sta si bate!",
	"470.Hristos domneste-n Sion",
	"471.Eu sunt un sol trimis",
	"472.Trambiti rasuna",
	"473.Salvat aproape",
	"474.Viata cum o duci,copile",
	"475.Iata,El vine,Domn in marire!",
	"476.Domnul curand Se coboara pe nor",
	"477.Domnul din cer coboara(canon)",
	"478.Mai sus de-albastre zari",
	"479.Cu Isus,ah,fata-n fata...",
	"480.O,vino,Tu,Emanuel!",
	"481.Isus,al vietii Domnitor",
	"482.Hristos,Cuvantul,a vorbit",
	"483.Trambiti sunati peste cer si pamant!",
	"484.Vesti de sfanta speranta",
	"485.Domnul vine pe alb nor(canon)",
	"486.Atata dor...",
	"487.Trambiti,sunati!",
	"488.Prin naltimi se-aude zvon",
	"489.Atat de aproape e Domnul!",
	"490.Voi,servii Domnului!",
	"491.Noi asteptam o,scump Isus!",
	"492.Tresaltati,vine Isus!",
	"493.Mi-e dor de cer",
	"494.Te-astept zilnic,Isuse!(canon)",
	"495.Va veni o zi",
	"496.Ai curaj,tresalta!",
	"497.Sfanta speranta!",
	"498.Hrist revine",
	"499.Acesta-i Salvatorul meu!",
	"500.Printre nori de osanale",
	"501.Cand El va veni",
	"502.Soapta vremii",
	"503.Sculati,caci Domnul vine",
	"504.Spune,tu,strajer trudit!",
	"505.Ascultati veste buna,popoare!",
	"506.Sculati,Domnul nostru vine!(canon)",
	"507. O veste buna pe inaltimi!",
	"508.Aleluia,Domnul vine!",
	"509.Ne pregatim de drum",
	"510.Sunt creat sa fiu iubire(canon)",
	"511.Domnul revine!",
	"512.Domnul pacii Se-arata",
	"513.Timpul de har e pe sfarsit!(canon)",
	"514.Timpul de har e pe sfarsit!(canon)",
	"515.Ziua cea mare e-asa de aproape!",
	"516.Fratilor,sosit e ceasul!",
	"517.Ai curaj,tu,turma mica!",
	"518.Desi nu stim cand",
	"519.Apocalipsa(canon)",
	"520.Sculati frati,toti!",
	"521.Bate ceasul vremii",
	"522.Sa priveghem!",
	"523.Sfarsitul veacului traim!",
	"524.Lasati lampile acum sa arda!",
	"525.Spuneti in lume!",
	"526.Luminezi tu,oare",
	"527.Glasul Domnului(canon)",
	"528.Se asterne frumos,peste suflet",
	"529.Auzi,goarna-ncepe sa sune!",
	"530.Fratilor,vedeti semnalul",
	"531.Ploaia tarzie,promisa",
	"532.Neguri destramate",
	"533.Vezi,pe nori El vine iar!",
	"534.Esti tu crestin adevarat",
	"535.Auzi un freamat mare",
	"536.Cand Isus,Domnul vietii,revine",
	"537.Acum se spune orisicui",
	"538.Din cer,din sfantul sanctuar",
	"539.Nu va pieri cel credincios",
	"540.Val de pace",
	"541.Eu stiu ca Domnul este viu",
	"542.In pace sta cel credincios",
	"543.Priveste la Domnul",
	"544.Glas de slava",
	"545.Revedea-ne-vom odata",
	"546.Las sa merg!",
	"547.Suntem straini si calatori",
	"548.Venim truditi",
	"549.Ne asteapta-un camin stralucit",
	"550.Ierusalim,oras slavit",
	"551.M-a cuprins un dor de casa",
	"552.Dor nestins de apa vie",
	"553.Exista o tara a lui Hristos",
	"554.O,sfant oras!",
	"555.Vreau sa cant azi un imn",
	"556.Mii de ingeri vestitori",
	"557.Cum ne va fi",
	"558.Exista tara stelelor",
	"559.Frumoasa tara",
	"560.Stim un rau cu apa vie",
	"561.Privesc cu dor spre Canaan",
	"562.Mi-e dor de-acasa!",
	"563.O,ce tara minunata",
	"564.Merg spre casa",
	"565.Iubesc poporul Tau!",
	"566.Ce placut e si frumos!",
	"567.Ce bine e cand fratii...",
	"568.Frumos e-aici cand ne-ntalnim",
	"569.Cine-mi este frate",
	"570.Suntem una-n iubirea Lui",
	"571.Ce pace si ce bucurie!",
	"572.S-ajunga-al nostru glas",
	"573.Acelasi nume toti purtam",
	"574.Suntem partasi in sfanta armonie",
	"575.Duh de iubire",
	"576.Dumnezeu e numai dragoste",
	"577.Aleluia, zi frumoasa!",
	"578.Marete Sabat",
	"579.O, sfant Sabat",
	"580.O, zi de bucurie",
	"581.Vedeti cum azi surade",
	"582.In ziua-a saptea ne-adunam",
	"583.Sabatul de Domnul dat noua",
	"584.O, ce bucurie",
	"585.Frumos e-al pacii sfant salas",
	"586.O, zi, popas divin",
	"587.Ce Sabat minunat",
	"588.Un nou Sabat",
	"589.Zi de Sabat, zi de har",
	"590.Si la lucru, si pe cale",
	"591.De la lucrul nostru",
	"592.Doamne, Tu esti Creatorul",
	"593.Din Paradis",
	"594.Porti de Sabat se deschid",
	"595.Cum va fi in vesnicie",
	"596.Astazi in ziua de Sabat",
	"597.E-atata cant...",
	"598.Dispara griji lumesti",
	"599.Cand umbra serii cade iar",
	"600.Dulce-i amurgul spre Sabat",
	"601.Un sabat ceresc",
	"602.Bine-ai venit, Sabat divin",
	"603.Cand seara s-a lasat",
	"604.Bine-ai venit, Sabat binecuvantat",
	"605.Ce scurta-mi pare a Domnului zi",
	"606.Ramai cu noi, e ziua pe sfarsite",
	"607.Apune soarele in vai",
	"608.Se insereaza peste zari",
	"609.O, scumpa Scoala de Sabat",
	"610.Cunosc un loc frumos",
	"611.O, priveste scoala noastra",
	"612.O, ce frumos e sa-nvatam",
	"613.Un loc placut si adorat",
	"614.Frumos si maret este-aici",
	"615.In ziua sfanta de Sabat",
	"616.Cum striga-un cerb",
	"617.Pe Dumnezeu rugati",
	"618.Sfant, sublim e locul Doamne",
	"619.Din ceruri, pentru mine",
	"620.Voi, care locuiti sub soare",
	"621.Veniti cu toti sa ne-nchinam",
	"622.Imn de lauda",
	"623.Tatal nostru cel din ceruri",
	"624.Iar, Isuse, ne-adunasi",
	"625.Varsa-Ti marea bunatate",
	"626.Laolalta ne-am strans",
	"627.Doamne sfinte, prea'ndurate",
	"628.Doamne sfinte, plin de mila",
	"629.Tatal nostru cel puternic",
	"630.Asteptam cu dor momentul",
	"631.Stam langa apa de viata",
	"632.Fii azi cu noi, Parinte bun",
	"633.Lasa, Doamne, binecuvantari",
	"634.Cu credinta-n fata Ta",
	"635.Bun Isus",
	"636.Cu pasi de ruga",
	"637.Vorbeste-mi, Tu, Isuse",
	"638.O, vorbeste-mi Tu, Isuse",
	"639.Deschide-mi ochii",
	"640.'Naltata spre unire",
	"641.Harul lui Isus",
	"642.Ramai cu a Ta mila",
	"643.Mana Ta, Isus",
	"644.Salom, salom",
	"645.Binecuvantarea Ta",
	"646.O, Doamne, Tu mi-ai dat",
	"647.O, cat as vrea sa-Ti multumesc",
	"648.Doamne, fii cu noi in veci de veci",
	"649.Dumnezeu cu noi pan'ne vedem",
	"650.Sa fie Domnul pavaza ta",
	"651.Cand si cum",
	"652.Scump Isuse, fa-ne azi",
	"653.Clipe solemne",
	"654.Cata iubire, cata jertfire",
	"655.Pierduta-n umbra mortii",
	"656.Ca ucenicii-n odaia de sus",
	"657.In umilinta ne-am plecat",
	"658.Frate drag, intinde mana",
	"659.Isus ne-a adunat in jurul mesei Lui",
	"660.O, cat de placut este locul",
	"661.Nu-i decat o Stanca vie",
	"662.Iti inchinam locasul",
	"663.Sfinteste, Doamne, casa Ta",
	"664a.Ti-aducem, Doamne-acesti copii",
	"664b.Ti-aducem, Doamne-acesti copii",
	"665.Pe masa e totul frumos asezat",
	"666.Bate ceasul vremii",
	"667.Ferice casa",
	"668.Ce fericit e-acel camin",
	"669.Revarsa, Doamne, pace si iubire",
	"670.In zori edenici",
	"671.Esti pe calea mantuirii",
	"672.Fiul meu, niciodata nu uita",
	"673.Dumnezeu, printr-o mama",
	"674.Un nume scump",
	"675.Din amurg de zare",
	"676.Taticul meu",
	"677.Inc-o zi de har trecu",
	"678.La ceas de asfintit",
	"679.Cand seara bland coboara",
	"680.Cand se lasa umbra serii",
	"681.O, cat e de tainic afara",
	"682.Daca pacea lin se lasa",
	"683.S-a-nnoptat",
	"684.Ziua trece usor",
	"685.O, Doamne, noaptea a venit",
	"686.Doamne, noaptea s-a lasat",
	"687.Cu soapte de-amurg",
	"688.Ramai cu pacea Ta",
	"689.Cu mireasma rugii sfinte",
	"690.Bland Pastor al vietii mele",
	"691.Pacea serii cade lin",
	"692.Iar o noapte-am odihnit",
	"693.Lasa harpa ta sa sune",
	"694.Isuse bland, lumina mea",
	"695.Bun sosit, o, zori frumoase",
	"696.Din nou se-arata o dimineata",
	"697.Dimineata a sosit",
	"698.In fiecare zori de zi",
	"699.Al tau sunt, Doamne",
	"700.Scump Isus, ajuta-mi Tu",
	"701.Doamne, pe cararea Ta",
	"702.Cu noi, cu toti, sa fie harul",
	"703.Toti copilasii ce vin la Isus",
	"704.Celui Sfant, marire",
	"705.Cand soarele se-arata iar",
	"706.Stii tu, oare, cate stele",
	"707.Tot ce e-n jurul nostru",
	"708.Cerul si pamantul",
	"709.Cine, oare, ne-a creat",
	"710.Oricate vrabii sunt pe gard",
	"711.Stau si privesc cerul minunat",
	"712.Scump Isus",
	"713.Eu cunosc un mielusel",
	"714.Sunt copil de Imparat",
	"715.N-aceasta zi frumoasa",
	"716.Pe maini, de dimineata",
	"717.Noaptea-n-cetisor se lasa",
	"718.De la El, din ceruri",
	"719.Voi, copii, din preajma noastra",
	"720.Vino-mi, Doamne-n ajutor",
	"721.Domnul vine",
	"722.Spre ceruri am pornit",
	"723.Al meu Parinte iubitor",
	"724.Ecoul unui cant",
	"725.Al lumii noastre firmament",
	"726.Ah, dulce e in flori bogat",
	"727.Campul iarasi a-nviat",
	"728.Spre zarile-albastre",
	"729.Vine primavara",
	"730.Inima e plina de avant",
	"731.Multi ani, cu pace si iubire",
	"732.Cantec plin de bucurie",
	"733.Azi, cantarea bucuriei",
	"734.Pe bratul Celui Preamarit",
	"735.Te preamarim, puternic Dumnezeu",
	"736.Sa te-asculte din Sion",
	"737.Bunul nostru Salvator",
	"738.O, sfant Miel fara vina",
	"739.Mariti cu toti",
	"740.Doamne din ceruri",
	"741.Din cer cu raza Ta",
	"742.Doamne, vin in fata Ta",
	"743.Liber in Domnul",
	"744.Fara-ncetare Hristos",
	"745.Eu am fost prea departe",
	"746.O inima schimbata",
	"747.Carte sfanta",
	"748.Fara de Tine",
	"749.Vreau sa fiu ca Tine",
	"750.Isuse bun, eterna Stea",
	"751.Domnul este scutul meu",
	"752.Cand nu stiu al meu drum",
	"753.O, cat de placut este locul",
	"754.Fii credincios",
	"755.Legea Ta",
	"756.De vezi pe cel flamand",
	"757.Un imn de slava",
	"758.Laudati pe Cel Preasfant",
	"759.Cu bucurie",
	"760.Valea umbrei mortii",
	"761.Departe-i patria din cer",
	"762.Se-aude un cant",
	"763.Chemare",
	"764.Cele trei solii",
	"765.Aleluia, zi cereasca",
	"766.O zi de Sabat",
	"767.Sarbatoarea Sabatului",
	"768.Cantare de Sabat",
	"769.Sfinte Parinte, Parinte-al iubirii",
	"770.Mama mea",
	"771.Doamne, slava-Ti se cuvine",
	"772.Tu esti Cel vrednic de marit",
	"773.Tatal nostru",
	"774.Doamne sfinte Creator",
	"775.De Cel Etern",
	"776.Lumina cea de aur",
	"777.Domnul Isus Hristos",
	"778.Un vesnic prieten am",
	"779.Isuse, Domn al lumilor",
	"780.Sa privim iubirea ce e in Isus",
	"781.Tu mi-esti speranta",
	"782.Din straluciri",
	"783.Priveste-a Domnului durere",
	"784.Un astru maret pe cer s-aratat",
	"785.O, Betleem",
	"786.Nainte-n lupta sfanta!",
	"787.Chiar asa mic cum sunt",
	"788.Doamne,Te rog!",
	"789.Ratacind departe",
	"790.Flori frumoase",
	"791.Din vremi strabune",
	"792.De multe ori,pustie",
	"793.Dorind fericirea",
	"794.Eu,ca crestin",
	"795.Mergand pe calea lui Isus",
	"796.Cu Cel Sfant incepe tot",
	"797.Iar cad frunzele padurii",
	"798.O,Isus,condu-ma Tu!",
	"799.Fost-a-un timp..",
	"800.Cu mult harul",
	"801.Florile Golgotei",
	"802.Privind spre Hristos",
	"803.Iubire si mila si pace",
	"804.Harul Domnului",
	"805.Ce placut e pentru Domnul",
	"806.Binecuvantarea",
	"807.Bland Pastor condu-ma Tu!",
	"808.Doamne,stii a mea iubire",
	"809.Sterge-ti fata plasa!",
	"810.Cand tu-mpovarat",
	"811.Ce bine e cand tot mereu",
	"812.Orice-ar veni azi peste noi",
	"813.Pe-ntinse valuri",
	"814.Furtuna e azi in juru-mi",
	"815.Cand ne gasim in mari nevoi",
	"816.Multi ingeri sfinti",
	"817.Eu nu Te las!",
	"818.Plin e de iubire",
	"819.Veniti,voi,toti cei credinciosi!",
	"820.Domnul,plin de mila",
	"821.Lasa-ti mintea sa se-ntoarca",
	"822.Hai,copile,vin la Mine!",
	"823.Iesiti cu toti,va bucurati!",
	"824.Auzi chemarea-Mi ingrijata!",
	"825.Galileea,Galileea",
	"826.Marire lui Isus cantam",
	"827.Din toata inima Te-ador,Isuse!",
	"828.Lasa inima sa cante!",
	"829.Fiica,fiica din Sion",
	"830.Oricati in Hristos se boteaza",
	"831.Plecam pe cai necunoscute",
	"832.Sa ducem Biblia-n popor!",
	"833.Iubirea Tatalui vestind",
	"834.Raspanditi lumina",
	"835.Noi plecam cu bucurie",
	"836.Samanta arunc-o",
	"837.Noi plecam in departari",
	"838.Ca peregrin",
	"839.Cand la sunetul de trambiti",
	"840.Ne vom revedea odata",
	"841.Ce frumos si dulce",
	"842.Cand odata va sa sune",
	"843.Cu Tine-n veci",
	"844.Cand vom trece noi odata",
	"845.Dincol' pe mal",
	"846.Cine-s acesti fericiti",
	"847.O,Tara mea!",
	"848.Un loc prea mandru",
	"849.Locui-vom noi vreodata",
	"850.Curand vom fi cu Domnu-n cer uniti",
	"851.Cetate cu de iaspis zid",
	"852.Tara mea,tara mea",
	"853.Veghetori,sunati din trambiti",
	"854.Mai este loc in portul",
	"855.Totul piere-n asta lume",
	"856.N-auziti un murmur dulce",
	"857.Rasuna printre rami de pom",
	"858.Un dulce vers de cant",
	"859.Cand de pe pamant",
	"860.Revederea",
	"861.La-acele tarmuri",
	"862.De ce-ntarzii,iubite frate",
	"863.Nu te scuza deloc",
	"864.Azi,daca-auzi..",
	"865.O,iata sta sa vina",
	"866.Ah,doar frunzis",
	"867.Al mortii ceas",
	"868.Te odihneste-n groapa ta!",
	"869.Catam acum loc de-odihnit",
	"870.Intr-o simtire",
	"871.Ne-adunam cu totii",
	"872.O,mama scumpa!",
	"873.Osana Regelui Isus!",
	"874.De inger Iosif noaptea...",
	"875.Eu sunt copil",
	"876.E noapte",
	"877.Frumoasa-i primavara",
	"878.Iauzi,cum canta asa de frumos",
	"879.Sus pe-o creanga de pom",
	"880.Dumnezeu-i de fata",
	"881.Doar Dumnezeu va fi marit",
	"882.Domnu-i iubirea",
	"883.Multumiti lui Dumnezeu",
	"884.Amicul cel mai bun in cer e",
	"885.Doamne,fi cu noi in veci de veci!",
	"886.Hristos,Eroul,a vorbit",
	"887.Pe cruce Domnu-a patimit",
	"888.Cand Isus Hristos Se pleaca spre noi",
	"889.Din radacina vie",
	"890.Doamne sfinte si-ndurate",
	"891.Vino la apa de viata!",
	"892.De mult ma lupt s-ajung mai sus",
	"893.Apa cristalina",
	"894.Sa pazesc,Isuse-nvata-ma,Legea Ta!",
	"895.Cine pe Isus gasit-a",
	"896.Biruitorul va primi sa guste",
	"897.Vezi cerul cum se-nnoreaza",
	"898.Cand iti pare ca-i grea crucea",
	"899.Fericit e tot acela",
	"900.Vin',izvor de viata sfanta!",
	"901.Varsa-Ti marea bunatate!",
	"902.Ah,Doamne,ia din pieptul meu",
	"903.Al vecerniei timp frumos",
	"904.Lasati lampile acum sa arda!",
	"905.Prin ruga totul se-mplineste",
	"906.Agatat de sfanta cruce",
	"907.De n-as avea in Domnul mangaiere...",
	"908.Iubit-ai Doamne,intreaga omenire",
	"909.Lucrarea,Doamne,este-a Ta",
	"910.As vrea sa duc in lume pacea Ta!",
	"911.Mi-e dor de-acas'",
	"912.Domnu-n curand",
	"913.Vezi,in nori El vine iara!",
	"914.Fratilor,sosit e ceasul",
	"915.Ziua cea mare e asa de-aproape!",
	"916.O,suflete-al meu",
	"917.Exista-o tara ca-n povesti",
	"918.Zi de Sabat,zi de har",
	"919.O,scumpa Scoala de Sabat",
	"920.Frumos e-al pacii sfant locas"
	};

int addRegistru(String entrada){
	FILE *fp = fopen(".Registru_Imnuri.txt", "ab+");
	
	char username[UNLEN+1];
	DWORD username_len = UNLEN+1;
	GetUserName(username, &username_len);
	
	time_t     now;
    struct tm *ts;
    char       buf[80];
	/* Obtener la hora actual */
    now = time(0);

    /* Formatear e imprimir el tiempo, "ddd yyyy-mm-dd hh:mm:ss zzz" */
    ts = localtime(&now);
    strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", ts);
	
	fprintf(fp, "\r\n%s - %s | IMN: %s\n", username, buf, entrada);
	fclose(fp);
}
	
int esNumero (String entrada){
	for (int i=0; i<strlen(entrada)-1; i++){
		if (!(entrada[i]>='0' && entrada[i]<='9')) return 0;
	}
	return 1;
}

int abrirNumero(int n){
	char ruta[3];
	char comandoFinal[26];
	char comando[]="start powerpnt ";
	char extension[]=".pptx";
	sprintf(ruta,"%03d", n);
	strcat(comandoFinal,comando);
	strcat(comandoFinal,ruta);
	strcat(comandoFinal,extension);
	if (n>0 && n<=920)	system(comandoFinal);
	else printf("\n	EROARE! Imnul trebuie sa fie intre 1 si 920.\n");
}

int buscarTitulo(String *nombres, String entrada){
	char cls[]="cls";
	char tmpNombres[100];
	int contador=0;
	entrada[strlen(entrada)-1]='\0';
	for(int i = 0; entrada[i]; i++){
		entrada[i] = tolower(entrada[i]);
	}
	if (strlen(entrada)==1) {
		printf("\n	Eroare! Introdu mai mult de o litera pentru a cauta un imn.\n");
		return 0;
	}
	if(strcmp(entrada, "clear") == 0) {
		system(cls);
		printf("%s", titluProgram);
		return 0;
	}
	if(strcmp(entrada, "exit") == 0) exit(0);
	if(strcmp(entrada, "help") == 0) {
		printf("\n	===COMENZI DISPONIBILE===\n\n");
		printf("	help	Ajutor\n	clear	Sterge textul scris din program\n	exit	Inchide programul\n\n");
	}
	else{
		for (int i=0; i<920; i++) {
			strcpy(tmpNombres, nombres[i]);
			for(int i = 0; tmpNombres[i]; i++) tmpNombres[i] = tolower(tmpNombres[i]);
			if(strstr(tmpNombres,entrada) != NULL) contador++;
		}
		if(strcmp(entrada, "clear")!=0) printf("\n	====== %d IMNURI GASITE ======\n\n", contador);
		for (int i=0; i<920; i++) {
			strcpy(tmpNombres, nombres[i]);
			for(int i = 0; tmpNombres[i]; i++) tmpNombres[i] = tolower(tmpNombres[i]);
			if(strstr(tmpNombres,entrada) != NULL) printf("	%s\n", nombres[i]);
		}
		if(contador==0 && (strcmp(entrada, "clear")!=0)) printf("	Nu s-a gasit nici un rezultat.\n");
		return 0;
	}
	
}

int main(){
char entrada[BUFFER_SIZE];
printf("%s", titluProgram);
	while (1){
		printf("\nIMN: ");
		fgets(entrada,BUFFER_SIZE, stdin); 
		fflush(stdin);
		if (esNumero(entrada)){
			int N = atoi(entrada);
			addRegistru(entrada);
			abrirNumero(N);
		}
		else{
			buscarTitulo(nombres, entrada);
		}		
	}
	return 0;
}